---

- name: create local ansible setup folder in user home
  file:
    path: "{{ ansible_env['HOME'] }}/ansible"
    state: directory
    mode: 0755

- name: create localsetup.json in your home folder
  template:
    src: localsetup.json.j2
    dest: "{{ ansible_env['HOME'] }}/ansible/localsetup.json"
    mode: 0644
    force: no

- name: create hosts in your home folder
  template:
    src: local_inventory.ini.j2
    dest: "{{ ansible_env['HOME'] }}/ansible/local_inventory.ini"
    mode: 0644
    force: no

- name: create mumble.json
  template:
    src: mumble.json.j2
    dest: "{{ ansible_env['HOME'] }}/ansible/mumble.json"
    mode: 0644
    force: no
