---

- name: install apache ssl modul
  become: true
  package:
    name: mod_ssl
    state: present

- name: Creates /etc/httpd/ssl directory
  become: true
  file:
    state: directory
    path: /etc/httpd/ssl
    mode: 0755

- name: check status of apache.key
  stat:
    path: /etc/httpd/ssl/apache.key
  register: apache_key_file

- name: check status of apache.ctr
  stat:
    path: /etc/httpd/ssl/apache.crt
  register: apache_ctr_file

- name: create key and crt
  become: true
  command: openssl req -x509 -newkey rsa:2048 -nodes  -subj "/C=DE/ST=Hamburg/L=Hamburg/O=privat/CN=${ansible_fqdn}" -days 365 -keyout /etc/httpd/ssl/apache.key -out /etc/httpd/ssl/apache.crt
  when: apache_key_file is not defined and apache_ctr_file is not defined

- name: set hostname in ssl.conf
  become: true
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: '[#]?ServerName '
    line: "ServerName {{ansible_fqdn}}:443"

- name: set SSLCertificateFile in ssl.conf
  become: true
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: 'SSLCertificateFile '
    line: "SSLCertificateFile /etc/httpd/ssl/apache.crt"

- name: set SSLCertificateKeyFile in ssl.conf
  become: true
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: 'SSLCertificateKeyFile '
    line: "SSLCertificateKeyFile /etc/httpd/ssl/apache.key"
