---

- name: open port 80 (http)
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: 80
    ctstate: NEW

- name: open port 443 (https)
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: 443
    ctstate: NEW
