---

- name: set user rights for /var/www/html/
  become: true
  file:
    path: /var/www/html
    state: directory
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755

- name: create index.html
  template:
    force: no
    src: index.html.j2 
    dest: /var/www/html/index.html
    mode: 0644

- name: add html root folder into home folder
  file:
    src: /var/www/html
    dest: ~/html
    state: directory
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    state: link

