---

- name: load current status of apache service
  command: systemctl status httpd.service
  register: httpd_status
  failed_when: 
    - httpd_status.rc != 0 # exit code normal 
    - httpd_status.rc != 3 # exit code when status inactiv
  changed_when: false

- name: systemctl add apache service to boot sequence
  become: true
  command: systemctl enable httpd.service
  when: not {{httpd_status.stdout  | search("enabled;") }}

- name: open port 80 (http)
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: 80
    ctstate: NEW

- name: open port 443 (https)
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
    destination_port: 443
    ctstate: NEW
