---

- name: load current status of apache service
  command: systemctl status httpd.service
  register: httpd_status
  failed_when: 
    - httpd_status.rc != 0 # exit code normal 
    - httpd_status.rc != 3 # exit code when status inactiv
  changed_when: false

- name: systemctl start apache service
  become: true
  command: systemctl start httpd.service
  when: not {{httpd_status.stdout  | search("active \(running\)") }}
