---

- name: install php
  become: true
  package:
    name: php
    state: present

- name: install php plugins
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php-mysql
    - php-xml
    - php-gd

- name: create info.php
  template:
    force: no
    src: info.php.j2 
    dest: /var/www/html/info.php
    mode: 0644

- name: systemctl restart apache service
  become: true
  command: systemctl restart httpd.service
