---
- name: install php plugins
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php-mysql
    - php-dom
    - php-mbstring
    - php-gd
    - php-pdo

- name: install mariadb-server
  become: true
  package:
    name: mariadb-server
    state: latest
