---
#https://www.howtoforge.com/apache_php_mysql_on_centos_7_lamp
- hosts: webserver
  become_method: su
  vars:
    ansible_become_pass: "{{ lookup('password', '~/ansible/root_pass.txt length=125 chars=ascii_letters,digits,hexdigits')}}"
    mysql_root_password: "{{ lookup('password', '~/ansible/mysql_root_pass.txt length=125 chars=ascii_letters,digits,hexdigits')}}"
  roles:
#    - apache
#    - php
    - mariadb
