---
#https://mumble.info/snapshot/murmur-static_x86-1.3.0~1797~g6ac0553~snapshot.tar.bz2
#https://wiki.mumble.info/wiki/Install_CentOS7
- hosts: webserver
  become_method: su
  vars:
    ansible_become_pass: "{{ lookup('password', '~/ansible/root_pass.txt length=125 chars=ascii_letters,digits,hexdigits')}}"
  roles:
    - mumble
