---
- hosts: webserver
  become_method: su
  vars:
    ansible_become_pass: "{{ lookup('password', '~/ansible/root_pass.txt length=125 chars=ascii_letters,digits,hexdigits')}}"
    force_build: true
  tasks:
    - name: startup mumble
      become: true
      service:
        name: murmur
        state: started